//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartCommander.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartCommander.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow only one Instance.
        /// </summary>
        public static string AllowOnlyOneInstance {
            get {
                return ResourceManager.GetString("AllowOnlyOneInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive {0} already exists..
        /// </summary>
        public static string ArchiveExists {
            get {
                return ResourceManager.GetString("ArchiveExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t copy files to the same directory.
        /// </summary>
        public static string CantCopyFileToItself {
            get {
                return ResourceManager.GetString("CantCopyFileToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit the folder.
        /// </summary>
        public static string CantEditFolder {
            get {
                return ResourceManager.GetString("CantEditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move files to the same directory.
        /// </summary>
        public static string CantMoveFileToItself {
            get {
                return ResourceManager.GetString("CantMoveFileToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move folder here.
        /// </summary>
        public static string CantMoveFolderHere {
            get {
                return ResourceManager.GetString("CantMoveFolderHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move folder to itself.
        /// </summary>
        public static string CantMoveFolderToItself {
            get {
                return ResourceManager.GetString("CantMoveFolderToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t view the folder.
        /// </summary>
        public static string CantViewFolder {
            get {
                return ResourceManager.GetString("CantViewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} to:.
        /// </summary>
        public static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Folder.
        /// </summary>
        public static string CreateNewFolder {
            get {
                return ResourceManager.GetString("CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current directory name.
        /// </summary>
        public static string CurrentDirectoryName {
            get {
                return ResourceManager.GetString("CurrentDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0}, folders: {1}..
        /// </summary>
        public static string CurrentDirInfo {
            get {
                return ResourceManager.GetString("CurrentDirInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Folder.
        /// </summary>
        public static string CurrentFolder {
            get {
                return ResourceManager.GetString("CurrentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete {0}?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder is not empty. Are you sure you would like to delete {0}?.
        /// </summary>
        public static string DeleteConfirmationNonEmpty {
            get {
                return ResourceManager.GetString("DeleteConfirmationNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} already exists..
        /// </summary>
        public static string DirectoryExists {
            get {
                return ResourceManager.GetString("DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Command Line.
        /// </summary>
        public static string DisplayCommandLine {
            get {
                return ResourceManager.GetString("DisplayCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Current Directory.
        /// </summary>
        public static string DisplayCurrentDirectory {
            get {
                return ResourceManager.GetString("DisplayCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Function Keys.
        /// </summary>
        public static string DisplayFunctionKeys {
            get {
                return ResourceManager.GetString("DisplayFunctionKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive is not available.
        /// </summary>
        public static string DriveNotAvailable {
            get {
                return ResourceManager.GetString("DriveNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: no pane selected.
        /// </summary>
        public static string ErrorNoPane {
            get {
                return ResourceManager.GetString("ErrorNoPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3 View.
        /// </summary>
        public static string F3View {
            get {
                return ResourceManager.GetString("F3View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4 Edit.
        /// </summary>
        public static string F4Edit {
            get {
                return ResourceManager.GetString("F4Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5 Copy.
        /// </summary>
        public static string F5Copy {
            get {
                return ResourceManager.GetString("F5Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6 Move.
        /// </summary>
        public static string F6Move {
            get {
                return ResourceManager.GetString("F6Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7 Create Folder.
        /// </summary>
        public static string F7CreateNewFolder {
            get {
                return ResourceManager.GetString("F7CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8 Delete.
        /// </summary>
        public static string F8Delete {
            get {
                return ResourceManager.GetString("F8Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Are you sure you would like to rewrite {0}?.
        /// </summary>
        public static string FileExistsRewrite {
            get {
                return ResourceManager.GetString("FileExistsRewrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name (for example, *.txt).
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Search.
        /// </summary>
        public static string FilesSearch {
            get {
                return ResourceManager.GetString("FilesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder already exists.
        /// </summary>
        public static string FolderExists {
            get {
                return ResourceManager.GetString("FolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        public static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Name:.
        /// </summary>
        public static string FtpName {
            get {
                return ResourceManager.GetString("FtpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous user.
        /// </summary>
        public static string IsAnonymous {
            get {
                return ResourceManager.GetString("IsAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        public static string ItemsNumber {
            get {
                return ResourceManager.GetString("ItemsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Configuration.
        /// </summary>
        public static string MenuConfiguration {
            get {
                return ResourceManager.GetString("MenuConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to FTP....
        /// </summary>
        public static string MenuConnectFTP {
            get {
                return ResourceManager.GetString("MenuConnectFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string MenuDisconnectFTP {
            get {
                return ResourceManager.GetString("MenuDisconnectFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        public static string MenuFTP {
            get {
                return ResourceManager.GetString("MenuFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Search.
        /// </summary>
        public static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by _date.
        /// </summary>
        public static string MenuSortByDate {
            get {
                return ResourceManager.GetString("MenuSortByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by _extension.
        /// </summary>
        public static string MenuSortByExtension {
            get {
                return ResourceManager.GetString("MenuSortByExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by _name.
        /// </summary>
        public static string MenuSortByName {
            get {
                return ResourceManager.GetString("MenuSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by _size.
        /// </summary>
        public static string MenuSortBySize {
            get {
                return ResourceManager.GetString("MenuSortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move {0} to:.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found: .
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation in Progress:.
        /// </summary>
        public static string OperationInProgress {
            get {
                return ResourceManager.GetString("OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Application restart required.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings on Exit.
        /// </summary>
        public static string SaveSettingsOnExit {
            get {
                return ResourceManager.GetString("SaveSettingsOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Window Position and Size.
        /// </summary>
        public static string SaveWindowPositionSize {
            get {
                return ResourceManager.GetString("SaveWindowPositionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in file content.
        /// </summary>
        public static string SearchFileContent {
            get {
                return ResourceManager.GetString("SearchFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in top directory only.
        /// </summary>
        public static string SearchTopDirectoryOnly {
            get {
                return ResourceManager.GetString("SearchTopDirectoryOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select existing FTP:.
        /// </summary>
        public static string SelectExistingFTP {
            get {
                return ResourceManager.GetString("SelectExistingFTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden/System Files.
        /// </summary>
        public static string ShowHiddenFiles {
            get {
                return ResourceManager.GetString("ShowHiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Confirmation when Deleting Non-empty Directory.
        /// </summary>
        public static string ShowNonEmptyConfirmation {
            get {
                return ResourceManager.GetString("ShowNonEmptyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Search.
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to stop the background operation?.
        /// </summary>
        public static string StopBackground {
            get {
                return ResourceManager.GetString("StopBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too large file size for viewing..
        /// </summary>
        public static string TooLargeSize {
            get {
                return ResourceManager.GetString("TooLargeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip.
        /// </summary>
        public static string Unzip {
            get {
                return ResourceManager.GetString("Unzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
